### PR TITLE
Fix LaunchAgents directory permissions, bail if `-install` is run with sudo

### LINKED ISSUE #76: puma-dev -install should warn if run under sudo
Just spent an unfortunate amount of time debugging this when it was my own fault! :sweat_smile:

It'd be really helpful if `puma-dev` could assist with this!

What happens when `-install` is run under sudo;
1. Launch agent and `~/Library/Application\ Support/io.puma.dev` get created as root
2. Launch agent is then run as root, which creates the log file (in your user directory) as root, which then causes the launch agent to silently fail to launch if you run it as your user!

It might be helpful for `-cleanup` to be able to detect and help with this situation, too!

### PR DESCRIPTION
**Pull request by nonrational**
Resolves https://github.com/puma/puma-dev/issues/141
Resolves #76

1. The permission bits used to create `~/Library/LaunchAgents` (if it doesn't exist) are incorrectly set to 0644 instead of 0755. This PR correctly sets it to 0755.
1. Since I was already touching setup, decided to knock out #76 as well. If you try to run `puma-dev install` under sudo, we bail out immediately.
image

## Changes
1. [x] Change `0644` to `0755` @ (_will_provide_link_)
1. [x] To enable testing, refactor `InstallIntoSystem` to take a struct for all its arguments.
1. [x] Add `setup_test.go` to verify that `InstallIntoSystem` creates the directory with the correct permissions.
1. [x] Given we can't test the "live" code without blowing away the ~/Library/LaunchAgents directory locally, write a makefile test that does the assets for us locally.
1. [x] ~~Write a test that ONLY runs on TravisCI machines that actually exercises the `-setup` main path. Not sure how that will go...~~ Punting on this. It's hairy.
1. [x] Ancillary: Limit DNS retry attempts to 3 instead of 10 to enable faster failure.
1. [x] Ancillary: Add golintci-lint config file
1. [x] Refuse to allow `-install` to run with `sudo`.

### CODE REVIEW

File: dev/setup_darwin.go [hunk 1]
```diff
@@ -183,16 +193,7 @@ func InstallIntoSystem(listenPort, tlsPort int, dir, domains, timeout string) er
 		return errors.Context(err, "loading plist into launchctl")
 	}
 
-	fmt.Printf("* Installed puma-dev on ports: http %d, https %d\n", listenPort, tlsPort)
-
-	return nil
-}
-
-func Stop() error {
```
Comment (nonrational) [inline dev/setup_darwin.go:191]: moved this to `stop.go`, since it's used in both linux and darwin (and doesn't have anything to do with setup)

File: dev/setup_darwin.go [hunk 2]
```diff
@@ -95,7 +95,17 @@ func Cleanup() {
...
-func InstallIntoSystem(listenPort, tlsPort int, dir, domains, timeout string) error {
+type InstallIntoSystemArgs struct {
+	ListenPort         int
+	TlsPort            int
+	LogfilePath        string
+	ApplinkDirPath     string
+	LaunchAgentDirPath string
+	Domains            string
+	Timeout            string
+}
```
Comment (nonrational) [inline dev/setup_darwin.go:106]: provide args type to approximate named function params.

File: dev/dns_test.go [hunk 3]
```diff
@@ -44,6 +44,7 @@ func TestServeDNS(t *testing.T) {
 
 				return nil
 			},
+			retry.Attempts(3),
```
Comment (nonrational) [inline dev/dns_test.go:47]: limit retries to 3 in tests to help fail faster. added while debugging another issue.

File: cmd/puma-dev/main_darwin.go [hunk 4]
```diff
@@ -59,7 +59,16 @@ func main() {
 	}
 
 	if *fInstall {
-		err := dev.InstallIntoSystem(*fInstallPort, *fInstallTLS, *fDir, *fDomains, (*fTimeout).String())
+		err := dev.InstallIntoSystem(&dev.InstallIntoSystemArgs{
+			ApplinkDirPath:     *fDir,
+			Domains:            *fDomains,
+			LaunchAgentDirPath: "~/Library/LaunchAgents",
+			ListenPort:         *fInstallPort,
+			LogfilePath:        "~/Library/Logs/puma-dev.log",
```
Comment (nonrational) [inline cmd/puma-dev/main_darwin.go:67]: probably a good idea to pull this out into shared variable, then add something like `puma-dev -f logs` (similar to `heroku -f logs`)

File: dev/setup_darwin.go [hunk 5]
```diff
@@ -154,20 +168,20 @@ func InstallIntoSystem(listenPort, tlsPort int, dir, domains, timeout string) er
...
+	logPath := homedir.MustExpand(config.LogfilePath)
+	plistDir := homedir.MustExpand(config.LaunchAgentDirPath)
+	plist := filepath.Join(plistDir, "io.puma.dev.plist")
+	dir := config.ApplinkDirPath
 
-	plistDir := homedir.MustExpand("~/Library/LaunchAgents")
-	plist := homedir.MustExpand("~/Library/LaunchAgents/io.puma.dev.plist")
-
-	err = os.MkdirAll(plistDir, 0644)
+	err = os.MkdirAll(plistDir, 0755)
```
Comment (nonrational) [inline dev/setup_darwin.go:176]: this is the bugfix.
