### PR TITLE
Fix serving public/index.html as a static file

### LINKED ISSUE #140: No static content serving on test domain
I'm coming from pow and wanted to use puma-dev now for me. I use a Mac with OSX 10.11.

I uninstalled `pow` with `curl get.pow.cx/uninstall.sh | sh`.

I installed puma-dev with:
`brew install puma/puma/puma-dev`

`puma-dev -V` gives `Version: 0.11 (go1.9.1)`.

Then i created a `~/.puma-dev` folder and following in it:
```
/testdomain/
/testdomain/public/
/testdomain/public/index.html
```
I started puma-dev with this command for testing:
`sudo puma-dev -d dev:test -http-port 80 -https-port 443 -debug`

When opening `http://testdomain.test` i get: `unexpected exit` as error.

I looked at the console and saw this:
```
* Directory for apps: /Users/murphy/.puma-dev
* Domains: dev, test
* DNS Server port: 9253
* HTTP Server port: 80
* HTTPS Server port: 443
! Puma dev listening on http and https
2017-12-11T16:53:28.782041466+01:00: GET '/' (host=testdomain.test)
! Booting app 'testdomain' on socket /Users/murphy/.puma-dev/testdomain/tmp/puma-dev-11110.sock
testdomain[11117]: Puma starting in single mode...
testdomain[11117]: * Version 3.11.0 (ruby 2.0.0-p648), codename: Love Song
testdomain[11117]: * Min threads: 0, max threads: 5
testdomain[11117]: * Environment: development
testdomain[11117]: ERROR: No application configured, nothing to run
! Killing 'testdomain' (11117)
* App 'testdomain' shutdown and cleaned up
! Detecting app 'testdomain' dying on start
2017-12-11T16:53:30.408110095+01:00: GET '/favicon.ico' (host=testdomain.test)
! Booting app 'testdomain' on socket /Users/murphy/.puma-dev/testdomain/tmp/puma-dev-11110.sock
testdomain[11118]: Puma starting in single mode...
testdomain[11118]: * Version 3.11.0 (ruby 2.0.0-p648), codename: Love Song
testdomain[11118]: * Min threads: 0, max threads: 5
testdomain[11118]: * Environment: development
testdomain[11118]: ERROR: No application configured, nothing to run
! Killing 'testdomain' (11118)
* App 'testdomain' shutdown and cleaned up
! Detecting app 'testdomain' dying on start
```

Here are my questions:
1. Did i miss something or is puma-dev not able to share static sites without config? ([Issue #44](https://github.com/puma/puma-dev/issues/44))
2. Why is puma started at all, since i think puma-dev should share the contents?

Thanks for all the help you can get me. I take all ideas :)

PS: Sorry for my bad english ;)

### PR DESCRIPTION
**Pull request by nonrational**
~~This PR serves to illustrate behavior discussed in #140 and #87.~~ 
Fixes #140 (at least the part of it that is not covered by #87) 

As of 0.13, `puma-dev` does not support serving "naked" static files without booting `puma`. It can, of course, be modified to support such behavior (see #87).

The headline here is https://github.com/puma/puma-dev/pull/234#discussion_r390653863

### Changes
- [x] link a bare-bones rack app (`static-site`) with a `public` directory containing `greeting.txt`
- [x] Ensure `GET localhost/greeting.txt` is handled by `puma-dev`
- [x] Ensure `GET localhost/foo` is handled by rack.
- [x] Fix `golint` warnings about using `Url` instead of `URL` variable names.  
- [x] use `ServeContent` to avoid redirecting `index.html` back to `/`. See https://github.com/puma/puma-dev/issues/140#issuecomment-597186114

### CODE REVIEW

**Comment by nonrational** [comment]
h/t @momolog for pushing on this issue and providing critical debugging feedback.

File: cmd/puma-dev/main_test.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func launchPumaDevBackgroundServerWithDefaults(t *testing.T) func() {
 	}
 }
 
-func getUrlWithHost(t *testing.T, url string, host string) string {
+func getURLWithHost(t *testing.T, url string, host string) string {
```
Comment (nonrational) [inline cmd/puma-dev/main_test.go]: golint wants `URL` not `Url`

File: etc/static-hi-puma/index.html [hunk 2]
```diff
@@ -0,0 +1 @@
+<html><h1>index.html</h1></html>
```
Comment (nonrational) [inline etc/static-hi-puma/index.html]: this should never show up. it's included here to verify that we weren't able to look outside the `public` directory.

File: dev/http.go [hunk 3]
```diff
@@ -147,12 +148,15 @@ func (h *HTTPServer) proxyReq(w http.ResponseWriter, req *http.Request) error {
...
-		path := filepath.Join(app.dir, "public", path.Clean(req.URL.Path))
+		safeURLPath := path.Clean(req.URL.Path)
+		path := filepath.Join(app.dir, "public", safeURLPath)
 
 		fi, err := os.Stat(path)
 		if err == nil && !fi.IsDir() {
-			http.ServeFile(w, req, path)
-			return httputil.ErrHandled
+			if ofile, err := os.Open(path); err == nil {
+				http.ServeContent(w, req, req.URL.Path, fi.ModTime(), io.ReadSeeker(ofile))
```
Comment (nonrational) [inline dev/http.go]: https://golang.org/pkg/net/http/#ServeFile

> As another special case, `ServeFile` redirects any request where `r.URL.Path` ends in "/index.html" to the same path, without the final "index.html". To avoid such redirects either modify the path or use `ServeContent`.

Comment (nonrational) [reply dev/http.go]: the downside with this approach is that you can't just drop an `index.html` in public and go to `mysite.localhost`. you have to navigate to `mysite.localhost/index.html`.

but, `puma-dev` never supported that anyway, given the `req.URL.Path != "/"`

I figure this is a good enhancement to consider when tackling #87

Comment (evanphx) [reply dev/http.go]: I think this is fine, your justification makes sense.
